format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: FREERTOS_CPU_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '48000000'}
  - type: Integer
    attributes: {id: FREERTOS_TICK_RATE_HZ}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1000'}
  - type: Integer
    attributes: {id: FREERTOS_TOTAL_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10240'}
- type: ElementPosition
  attributes: {x: '15', y: '587', id: FreeRTOS}
