format_version: v1.0
type: UniqueComponent
attributes: {id: tc4}
children:
- type: Symbols
  children:
  - type: Comment
    attributes: {id: TC_COMPARE_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Compare Period is 32.0 us ****'}
  - type: KeyValueSet
    attributes: {id: TC_CTRLA_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc4, value: '750000'}
  - type: Comment
    attributes: {id: TC_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Timer resolution is 1333.33333333 nS****'}
  - type: Boolean
    attributes: {id: TC_TIMER_EVCTRL_OVFEO}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TC_TIMER_INTENSET_OVF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc4, value: '93'}
  - type: Float
    attributes: {id: TC_TIMER_TIME_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '87381.336'}
    - type: Values
      children:
      - type: User
        attributes: {value: '125.0'}
  - type: Combo
    attributes: {id: TC_TIMER_UNIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: microsecond}
- type: ElementPosition
  attributes: {x: '157', y: '345', id: tc4}
